In [1]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler

titanic = sns.load_dataset('titanic')

features = ['sex', 'age', 'fare', 'class', 'embark_town', 'alone']
X = titanic[features].copy()
X.head()

      sex   age     fare  class  embark_town  alone
0    male  22.0   7.2500  Third  Southampton  False
1  female  38.0  71.2833  First    Cherbourg  False
2  female  26.0   7.9250  Third  Southampton   True
3  female  35.0  53.1000  First  Southampton  False
4    male  35.0   8.0500  Third  Southampton   True

In [2]:
print(X.isnull().sum())

X['age'] = X['age'].fillna(X['age'].median())
X['embark_town'] = X['embark_town'].fillna(X['embark_town'].mode()[0])

max_fare = X['fare'].mean() + (3 * X['fare'].std())
X['fare'] = X['fare'].clip(upper=max_fare)

sex              0
age            177
fare             0
class            0
embark_town      2
alone            0
dtype: int64

In [3]:
le = LabelEncoder()
text_cols = ['sex', 'class', 'embark_town', 'alone']

for col in text_cols:
    X[col] = le.fit_transform(X[col].astype(str))

X.head()

   sex   age     fare  class  embark_town  alone
0    1  22.0   7.2500      2            2      0
1    0  38.0  71.2833      0            0      0
2    0  26.0   7.9250      2            2      1
3    0  35.0  53.1000      0            2      0
4    1  35.0   8.0500      2            2      1

In [4]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Cleaned feature matrix shape:", X_scaled.shape)

Cleaned feature matrix shape: (891, 6)